# cargo-deny configuration file
# https://embarkstudios.github.io/cargo-deny/

[advisories]
# Advisory database sources
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

# Advisory severity levels to check
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"

# Ignore advisories for specific crates (use sparingly)
ignore = [
    # Example: "RUSTSEC-2020-0001",
]

[licenses]
# License policy
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
]
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
# Dependency bans
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

# Skip certain crates when checking for duplicates
skip = [
    # Windows-specific crates that commonly have multiple versions
    { name = "windows_*", version = "*" },
    { name = "winapi*", version = "*" },
]

# Deny specific crates
deny = [
    # Add problematic crates here
    # { name = "openssl", version = "*" },  # Example
]

# Skip dependency trees for certain crates
skip-tree = [
    # Add crates whose dependency trees should be ignored
    # { name = "criterion", version = "*" },  # Example for dev deps
]

[sources]
# Source policy
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []