# cargo-deny configuration file
# https://embarkstudios.github.io/cargo-deny/

[advisories]
# Advisory database sources
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

# Ignore advisories for specific crates (use sparingly)
ignore = [
    # Example: "RUSTSEC-2020-0001",
]

[licenses]
# License policy
private = { ignore = true }
allow = [
    "MIT",
    "Apache-2.0", 
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
]
exceptions = [
    # Allow specific crates to use otherwise-banned licenses
]

[bans]
# Dependency bans
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

# Skip certain crates when checking for duplicates  
skip = [
    # Windows-specific crates that commonly have multiple versions
    { name = "windows_*", version = "*" },
    { name = "winapi*", version = "*" },
]

# Deny specific crates
deny = [
    # Add problematic crates here
]

# Skip dependency trees for certain crates
skip-tree = [
    # Add crates whose dependency trees should be ignored
]

[sources]
# Source policy
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []